version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: API
    build:
      context: .
      dockerfile: src/API/Dockerfile
    depends_on:
      - mssql
    ports:
      - 5000:8080
      - 5001:8081

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=admin.123
      - MSSQL_PID=Developer
      - MSSQL_DB=fast-clean-architecture
    volumes:
      - ./.containers/mssql:/var/opt/mssql
    ports:
      - 1433:1433