name: Package

on:
  push:
    tags: 
      - release/*
    paths:
      - 'FastCleanArchitecture.nuspec'
  
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NuGet.org

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: nuget/setup-nuget@v1
        name: Setup NuGet
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: nuget pack FastCleanArchitecture.nuspec -NoDefaultExcludes
        
      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate